# frozen_string_literal: true

source "https://rubygems.org"

gem "benchmarker"

gem "rack"
#gem "rocketrouter"
gem "rack-jet_router"
gem "keight"
#gem "hanami"
gem "hanami-router"
gem "rack-multiplexer"
gem "sinatra"
